// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKpWlIFkqqjZsJKyDmd8uDS-VGHuNAtnY',
    appId: '1:822736118661:web:671bbc15a6c5561e7f1aec',
    messagingSenderId: '822736118661',
    projectId: 'chatapp-4a9e1',
    authDomain: 'chatapp-4a9e1.firebaseapp.com',
    storageBucket: 'chatapp-4a9e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxYK4SCyS5BMzvRXcGBLmlhAIK36HUJwI',
    appId: '1:822736118661:android:c02e74aac1b91cb37f1aec',
    messagingSenderId: '822736118661',
    projectId: 'chatapp-4a9e1',
    storageBucket: 'chatapp-4a9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfPRsI-k_DgcoJi7QmwPApQRl4i80Yp4U',
    appId: '1:822736118661:ios:f549837d532decf07f1aec',
    messagingSenderId: '822736118661',
    projectId: 'chatapp-4a9e1',
    storageBucket: 'chatapp-4a9e1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfPRsI-k_DgcoJi7QmwPApQRl4i80Yp4U',
    appId: '1:822736118661:ios:f549837d532decf07f1aec',
    messagingSenderId: '822736118661',
    projectId: 'chatapp-4a9e1',
    storageBucket: 'chatapp-4a9e1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWD5mS6NEPAMAJQGHD4xyw-xU4-BUSGCM',
    appId: '1:822736118661:web:1e9e77fb64a9517a7f1aec',
    messagingSenderId: '822736118661',
    projectId: 'chatapp-4a9e1',
    authDomain: 'chatapp-4a9e1.firebaseapp.com',
    storageBucket: 'chatapp-4a9e1.firebasestorage.app',
  );
}
